/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteCtrl;
import controller.ProductoCtrl;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanes
 */
public class Factura extends javax.swing.JInternalFrame {

    int numeroCampos = 1;
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscarCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarClienteFactura = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombreBuscado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoProductoBuscado = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtProductoBuscado = new javax.swing.JTextField();
        btnAgregarProductoFactura = new javax.swing.JButton();
        btnEliminarProductoFactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductosFactura = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadFactura = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Codigo cliente:");

        jLabel2.setText("Gestionar Factura");

        btnBuscarClienteFactura.setText("Buscar Cliente");
        btnBuscarClienteFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteFacturaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre cliente:");

        txtNombreBuscado.setEditable(false);
        txtNombreBuscado.setFocusable(false);

        jLabel4.setText("codigo producto a comprar:");

        btnBuscarProducto.setText("Buscar Producto");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jLabel5.setText("Informacion:");

        txtProductoBuscado.setEditable(false);
        txtProductoBuscado.setFocusable(false);

        btnAgregarProductoFactura.setText("Agregar producto");
        btnAgregarProductoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoFacturaActionPerformed(evt);
            }
        });

        btnEliminarProductoFactura.setText("Eliminar producto");

        tblProductosFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(tblProductosFactura);

        jLabel6.setText("Cantidad comprada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarClienteFactura))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoProductoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarProducto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProductoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadFactura)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarProductoFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarProductoFactura))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClienteFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigoProductoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProductoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProductoFactura)
                    .addComponent(btnEliminarProductoFactura)
                    .addComponent(jLabel6)
                    .addComponent(txtCantidadFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteFacturaActionPerformed
        int codigo = Integer.parseInt(txtBuscarCodigo.getText());
        ClienteCtrl.instancia().buscarClientePorNumIdentidad(codigo);
        if(ClienteCtrl.instancia().getCliente() == null){
            JOptionPane.showMessageDialog(this, "El cliente debe de estar registrado para facturar");
            limpiarCamposCliente();
        }else{
            txtNombreBuscado.setText(ClienteCtrl.instancia().getCliente().getNombre().concat(" ")
                    .concat(ClienteCtrl.instancia().getCliente().getApellido())); 
        }
    }//GEN-LAST:event_btnBuscarClienteFacturaActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        int codigo = Integer.parseInt(txtCodigoProductoBuscado.getText());
        ProductoCtrl.instancia().buscarProductoPorCodigo(codigo);
        if(ProductoCtrl.instancia().getProducto()== null){
            JOptionPane.showMessageDialog(this, "El producto no se encuentra regustrado");
            limpiarCamposProducto();
        }else{
            txtProductoBuscado.setText(ProductoCtrl.instancia().getProducto().getNombre().concat(" , Precio: ")
                    .concat(Double.toString(ProductoCtrl.instancia().getProducto().getPrecio()))); 
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnAgregarProductoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoFacturaActionPerformed
        ListarProducto();
        //numeroCampos = numeroCampos + 1;
        limpiarCamposProducto();
        
    }//GEN-LAST:event_btnAgregarProductoFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProductoFactura;
    private javax.swing.JButton btnBuscarClienteFactura;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEliminarProductoFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProductosFactura;
    private javax.swing.JTextField txtBuscarCodigo;
    private javax.swing.JTextField txtCantidadFactura;
    private javax.swing.JTextField txtCodigoProductoBuscado;
    private javax.swing.JTextField txtNombreBuscado;
    private javax.swing.JTextField txtProductoBuscado;
    // End of variables declaration//GEN-END:variables

    public void ListarProducto(){
        DefaultTableModel producto;
        producto = new DefaultTableModel(){ 
            
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        producto.addColumn("Codigo");
        producto.addColumn("Nombre");
        producto.addColumn("Precio");
        producto.addColumn("Cantidad");
        
        //modelo.setValueAt(dato, fila, columna);
        

        Object fila[] =  new Object[producto.getColumnCount()];
        for(int i=0;i<numeroCampos;i++){
           ProductoCtrl.instancia().getProducto();
           
           fila[0] = ProductoCtrl.instancia().getProducto().getCodigo();
           fila[1] = ProductoCtrl.instancia().getProducto().getNombre();
           fila[2] = ProductoCtrl.instancia().getProducto().getPrecio();
           fila[3] = txtCantidadFactura.getText();
           producto.addRow(fila);
        }
        tblProductosFactura.setModel(producto);
        numeroCampos++;
    }
    
    public void limpiarCamposCliente(){
        txtBuscarCodigo.setText("");
        txtNombreBuscado.setText("");
    }
    public void limpiarCamposProducto(){
        txtCodigoProductoBuscado.setText("");
        txtProductoBuscado.setText("");
        txtCantidadFactura.setText("");
    }
}
